language: node_js
node_js:
  - '16'  

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - zip -r -q travis_app.zip .

before_deploy:
  - pip install --user awscli 

deploy:
  provider: script
  script: aws s3 cp /home/travis/build/maheshkaldhone/aws-portfolio/build_artifact.zip s3://travisdemobuilds
  skip_cleanup: true
  on:
    branch: main
