language: node_js
node_js:
  - '16'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ls -al
  - pwd
  - npm run build
  - ls -al ./build
  - zip -r -q travis_app.zip .
  - ls -al

before_deploy:
  - pip install --user awscli

deploy:
  - provider: elasticbeanstalk
    region: "us-east-2"
    app: "travis-ci"
    env: "Travis-ci-dev"  # Main environment for production
    bucket_name: "travisdemobuilds"
    bucket_path: "DEV"
    skip_cleanup: true
    on:
      branch: main  # Only deploy to Elastic Beanstalk on main branch

  - provider: elasticbeanstalk
    region: "us-east-2"
    app: "travis-ci"
    env: "Travis-ci-qa"  # QA environment
    bucket_name: "travisdemobuilds"
    bucket_path: "QA"
    skip_cleanup: true
    on:
      branch: QA  # Deploy to Elastic Beanstalk on QA branch
