language: node_js
node_js:
  - '16'  

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - zip -r -q travis_app.zip .

before_deploy:
  - pip install --user awscli 

# deploy:
#   provider: script
#   script: aws s3 cp /home/travis/build/maheshkaldhone/aws-portfolio/build_artifact.zip s3://travisdemobuilds
#   skip_cleanup: true
#   on:
#     branch: main

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "travis-ci"
#   env: "Travis-ci-env"
#   bucket_name: "travisdemobuilds"
#   skip_cleanup: true
#   on:
#     branch: main

# # Deploy to production (main branch)
 deploy:
   - provider: elasticbeanstalk
     region: "us-east-2"
     app: "travis-ci"
     env: "Travis-ci-dev"
     bucket_name: "travisdemobuilds"
     bucket_path: "DEV"
     skip_cleanup: true
     on:
       branch: main

 # Deploy to QA (qa branch)
   - provider: elasticbeanstalk
     region: "us-east-2"
     app: "travis-ci"
     env: "Travis-ci-qa"
     bucket_name: "travisdemobuilds"
     bucket_path: "QA"
     skip_cleanup: true
     on:
       branch: QA
