language: node_js
node_js:
  - '16'

cache:
  directories:
    - node_modules

stages:
  - name: build
  - name: test
  - name: deploy
    if: branch = main 
    
jobs:
  include:
    - stage: build
      script:
        - npm install
        - npm run build
        - zip -r -q travis_app.zip .

    - stage: test
      script:
        - npm run lint
        - npm test

    - stage: deploy
      before_deploy:
        - pip install --user awscli
      deploy:
        - provider: elasticbeanstalk
          region: "us-east-2"
          app: "Travis-ci"
          env: "Travis-ci-dev"
          bucket_name: "travisdemobuilds"
          bucket_path: "DEV"
          skip_cleanup: true
          on:
            branch: main
