language: node_js
node_js:
  - '16'  

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ls -al 
  - pwd
  - npm run build
  - ls -al ./build
  - zip -r -q travis_app.zip .
  - ls -al 
  
before_deploy:
  - pip install --user awscli 

deploy:
  provider: script
  script: aws s3 cp /home/travis/build/maheshkaldhone/travis-ci/travis_app.zip s3://travisdemobuilds
  skip_cleanup: true
  on:
    branch: main
